# Generated by Django 3.1.5 on 2021-05-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackoverflowuser',
            name='about_me',
            field=models.TextField(default='안녕하세요~'),
        ),
    ]
